# Build:
#   docker build -t registry.gitlab.com/wave-engineering/spreadsheet/builder:latest
# Push:
#   docker push registry.gitlab.com/wave-engineering/spreadsheet/builder

FROM python:3.7.2-alpine

RUN apk add --no-cache nodejs npm make git
